// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/example.proto

package tensorflow

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Example struct {
	Features             *Features `protobuf:"bytes,1,opt,name=features,proto3" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Example) Reset()         { *m = Example{} }
func (m *Example) String() string { return proto.CompactTextString(m) }
func (*Example) ProtoMessage()    {}
func (*Example) Descriptor() ([]byte, []int) {
	return fileDescriptor_15c5bf3911628c3c, []int{0}
}

func (m *Example) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Example.Unmarshal(m, b)
}
func (m *Example) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Example.Marshal(b, m, deterministic)
}
func (m *Example) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Example.Merge(m, src)
}
func (m *Example) XXX_Size() int {
	return xxx_messageInfo_Example.Size(m)
}
func (m *Example) XXX_DiscardUnknown() {
	xxx_messageInfo_Example.DiscardUnknown(m)
}

var xxx_messageInfo_Example proto.InternalMessageInfo

func (m *Example) GetFeatures() *Features {
	if m != nil {
		return m.Features
	}
	return nil
}

type SequenceExample struct {
	Context              *Features     `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	FeatureLists         *FeatureLists `protobuf:"bytes,2,opt,name=feature_lists,json=featureLists,proto3" json:"feature_lists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SequenceExample) Reset()         { *m = SequenceExample{} }
func (m *SequenceExample) String() string { return proto.CompactTextString(m) }
func (*SequenceExample) ProtoMessage()    {}
func (*SequenceExample) Descriptor() ([]byte, []int) {
	return fileDescriptor_15c5bf3911628c3c, []int{1}
}

func (m *SequenceExample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SequenceExample.Unmarshal(m, b)
}
func (m *SequenceExample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SequenceExample.Marshal(b, m, deterministic)
}
func (m *SequenceExample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SequenceExample.Merge(m, src)
}
func (m *SequenceExample) XXX_Size() int {
	return xxx_messageInfo_SequenceExample.Size(m)
}
func (m *SequenceExample) XXX_DiscardUnknown() {
	xxx_messageInfo_SequenceExample.DiscardUnknown(m)
}

var xxx_messageInfo_SequenceExample proto.InternalMessageInfo

func (m *SequenceExample) GetContext() *Features {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *SequenceExample) GetFeatureLists() *FeatureLists {
	if m != nil {
		return m.FeatureLists
	}
	return nil
}

func init() {
	proto.RegisterType((*Example)(nil), "tensorflow.Example")
	proto.RegisterType((*SequenceExample)(nil), "tensorflow.SequenceExample")
}

func init() { proto.RegisterFile("tensorflow/example.proto", fileDescriptor_15c5bf3911628c3c) }

var fileDescriptor_15c5bf3911628c3c = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x49, 0xcd, 0x2b,
	0xce, 0x2f, 0x4a, 0xcb, 0xc9, 0x2f, 0xd7, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0xc8, 0x48, 0x21, 0xab, 0x4a, 0x4b, 0x4d, 0x2c, 0x29,
	0x2d, 0x82, 0xaa, 0x52, 0xb2, 0xe6, 0x62, 0x77, 0x85, 0x68, 0x13, 0x32, 0xe0, 0xe2, 0x80, 0xca,
	0x15, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x89, 0xe8, 0x21, 0xf4, 0xe9, 0xb9, 0x41, 0xe5,
	0x82, 0xe0, 0xaa, 0x94, 0x1a, 0x18, 0xb9, 0xf8, 0x83, 0x53, 0x0b, 0x4b, 0x53, 0xf3, 0x92, 0x53,
	0x61, 0xa6, 0xe8, 0x71, 0xb1, 0x27, 0xe7, 0xe7, 0x95, 0xa4, 0x56, 0x94, 0xe0, 0x35, 0x04, 0xa6,
	0x48, 0xc8, 0x96, 0x8b, 0x17, 0x6a, 0x5e, 0x7c, 0x4e, 0x66, 0x71, 0x49, 0xb1, 0x04, 0x13, 0x58,
	0x97, 0x04, 0x16, 0x5d, 0x3e, 0x20, 0xf9, 0x20, 0x9e, 0x34, 0x24, 0x9e, 0x13, 0x4f, 0x14, 0x92,
	0x3f, 0x93, 0xd8, 0xc0, 0x9e, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x32, 0xdb, 0x11,
	0x16, 0x01, 0x00, 0x00,
}
