// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/bigchange/go-pro/proto/service.proto

package tfdemo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edb595bf792f25f, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Request) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Response struct {
	Sum                  float32  `protobuf:"fixed32,1,opt,name=sum,proto3" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0edb595bf792f25f, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSum() float32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "tfdemo.Request")
	proto.RegisterType((*Response)(nil), "tfdemo.Response")
}

func init() {
	proto.RegisterFile("github.com/bigchange/go-pro/proto/service.proto", fileDescriptor_0edb595bf792f25f)
}

var fileDescriptor_0edb595bf792f25f = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0xdd, 0xca, 0x82, 0x40,
	0x10, 0x40, 0x59, 0x05, 0xbf, 0x8f, 0x21, 0x48, 0xf6, 0x4a, 0xa2, 0x8b, 0x10, 0x02, 0x6f, 0xda,
	0x85, 0x82, 0x1e, 0x44, 0x9f, 0x20, 0x6d, 0x5a, 0xbd, 0x58, 0x67, 0xdb, 0x9f, 0xd0, 0xb7, 0x0f,
	0x5d, 0xa1, 0xbb, 0x39, 0xc3, 0x70, 0xce, 0x80, 0x54, 0x83, 0xef, 0x43, 0x2b, 0x3a, 0xd2, 0xb2,
	0x1d, 0x54, 0xd7, 0x3f, 0x46, 0x85, 0x52, 0xd1, 0xc5, 0x58, 0x92, 0xc6, 0x92, 0x27, 0xe9, 0xd0,
	0x7e, 0x86, 0x0e, 0xc5, 0x4a, 0x3c, 0xf3, 0xaf, 0x27, 0x6a, 0x2a, 0xcf, 0xf0, 0x57, 0xe3, 0x3b,
	0xa0, 0xf3, 0x7c, 0x07, 0x6c, 0x2a, 0xd8, 0x89, 0x55, 0x49, 0xcd, 0xa6, 0x85, 0xe6, 0x22, 0x89,
	0x34, 0x97, 0x47, 0xf8, 0xaf, 0xd1, 0x19, 0x1a, 0x1d, 0xf2, 0x1c, 0x52, 0x17, 0xf4, 0x76, 0xb9,
	0x8c, 0xd7, 0x3b, 0x40, 0x13, 0x74, 0x13, 0x03, 0xbc, 0x82, 0xb4, 0x09, 0x9a, 0xef, 0x45, 0x4c,
	0x88, 0xcd, 0x7f, 0xc8, 0x7f, 0x8b, 0x68, 0x6a, 0xb3, 0xf5, 0x97, 0xdb, 0x37, 0x00, 0x00, 0xff,
	0xff, 0x3f, 0x05, 0x49, 0x76, 0xbe, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SumServiceClient is the client API for SumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SumServiceClient interface {
	Sum(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type sumServiceClient struct {
	cc *grpc.ClientConn
}

func NewSumServiceClient(cc *grpc.ClientConn) SumServiceClient {
	return &sumServiceClient{cc}
}

func (c *sumServiceClient) Sum(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/tfdemo.SumService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SumServiceServer is the server API for SumService service.
type SumServiceServer interface {
	Sum(context.Context, *Request) (*Response, error)
}

// UnimplementedSumServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSumServiceServer struct {
}

func (*UnimplementedSumServiceServer) Sum(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}

func RegisterSumServiceServer(s *grpc.Server, srv SumServiceServer) {
	s.RegisterService(&_SumService_serviceDesc, srv)
}

func _SumService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SumServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tfdemo.SumService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SumServiceServer).Sum(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _SumService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tfdemo.SumService",
	HandlerType: (*SumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _SumService_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/bigchange/go-pro/proto/service.proto",
}
