// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow_serving/input.proto

package tensorflow_serving

import (
	fmt "fmt"
	math "math"

	tensorflow "github.com/bigchange/go-pro/tensorflow"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Specifies one or more fully independent input Examples.
// See examples at:
//     https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/example/example.proto
type ExampleList struct {
	Examples             []*tensorflow.Example `protobuf:"bytes,1,rep,name=examples,proto3" json:"examples,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ExampleList) Reset()         { *m = ExampleList{} }
func (m *ExampleList) String() string { return proto.CompactTextString(m) }
func (*ExampleList) ProtoMessage()    {}
func (*ExampleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_4595aa0586506d9d, []int{0}
}

func (m *ExampleList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleList.Unmarshal(m, b)
}
func (m *ExampleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleList.Marshal(b, m, deterministic)
}
func (m *ExampleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleList.Merge(m, src)
}
func (m *ExampleList) XXX_Size() int {
	return xxx_messageInfo_ExampleList.Size(m)
}
func (m *ExampleList) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleList.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleList proto.InternalMessageInfo

func (m *ExampleList) GetExamples() []*tensorflow.Example {
	if m != nil {
		return m.Examples
	}
	return nil
}

// Specifies one or more independent input Examples, with a common context
// Example.
//
// The common use case for context is to cleanly and optimally specify some
// features that are common across multiple examples.
//
// See example below with a search query as the context and multiple restaurants
// to perform some inference on.
//
// context: {
//   feature: {
//     key  : "query"
//     value: {
//       bytes_list: {
//         value: [ "pizza" ]
//       }
//     }
//   }
// }
// examples: {
//   feature: {
//     key  : "cuisine"
//     value: {
//       bytes_list: {
//         value: [ "Pizzeria" ]
//       }
//     }
//   }
// }
// examples: {
//   feature: {
//     key  : "cuisine"
//     value: {
//       bytes_list: {
//         value: [ "Taqueria" ]
//       }
//     }
//   }
// }
//
// Implementations of ExampleListWithContext merge the context Example into each
// of the Examples. Note that feature keys must not be duplicated between the
// Examples and context Example, or the behavior is undefined.
//
// See also:
//     tensorflow/core/example/example.proto
//     https://developers.google.com/protocol-buffers/docs/proto3#maps
type ExampleListWithContext struct {
	Examples             []*tensorflow.Example `protobuf:"bytes,1,rep,name=examples,proto3" json:"examples,omitempty"`
	Context              *tensorflow.Example   `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ExampleListWithContext) Reset()         { *m = ExampleListWithContext{} }
func (m *ExampleListWithContext) String() string { return proto.CompactTextString(m) }
func (*ExampleListWithContext) ProtoMessage()    {}
func (*ExampleListWithContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_4595aa0586506d9d, []int{1}
}

func (m *ExampleListWithContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleListWithContext.Unmarshal(m, b)
}
func (m *ExampleListWithContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleListWithContext.Marshal(b, m, deterministic)
}
func (m *ExampleListWithContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleListWithContext.Merge(m, src)
}
func (m *ExampleListWithContext) XXX_Size() int {
	return xxx_messageInfo_ExampleListWithContext.Size(m)
}
func (m *ExampleListWithContext) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleListWithContext.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleListWithContext proto.InternalMessageInfo

func (m *ExampleListWithContext) GetExamples() []*tensorflow.Example {
	if m != nil {
		return m.Examples
	}
	return nil
}

func (m *ExampleListWithContext) GetContext() *tensorflow.Example {
	if m != nil {
		return m.Context
	}
	return nil
}

type Input struct {
	// Types that are valid to be assigned to Kind:
	//	*Input_ExampleList
	//	*Input_ExampleListWithContext
	Kind                 isInput_Kind `protobuf_oneof:"kind"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_4595aa0586506d9d, []int{2}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

type isInput_Kind interface {
	isInput_Kind()
}

type Input_ExampleList struct {
	ExampleList *ExampleList `protobuf:"bytes,1,opt,name=example_list,json=exampleList,proto3,oneof"`
}

type Input_ExampleListWithContext struct {
	ExampleListWithContext *ExampleListWithContext `protobuf:"bytes,2,opt,name=example_list_with_context,json=exampleListWithContext,proto3,oneof"`
}

func (*Input_ExampleList) isInput_Kind() {}

func (*Input_ExampleListWithContext) isInput_Kind() {}

func (m *Input) GetKind() isInput_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *Input) GetExampleList() *ExampleList {
	if x, ok := m.GetKind().(*Input_ExampleList); ok {
		return x.ExampleList
	}
	return nil
}

func (m *Input) GetExampleListWithContext() *ExampleListWithContext {
	if x, ok := m.GetKind().(*Input_ExampleListWithContext); ok {
		return x.ExampleListWithContext
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Input) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Input_ExampleList)(nil),
		(*Input_ExampleListWithContext)(nil),
	}
}

func init() {
	proto.RegisterType((*ExampleList)(nil), "tensorflow.serving.ExampleList")
	proto.RegisterType((*ExampleListWithContext)(nil), "tensorflow.serving.ExampleListWithContext")
	proto.RegisterType((*Input)(nil), "tensorflow.serving.Input")
}

func init() { proto.RegisterFile("tensorflow_serving/input.proto", fileDescriptor_4595aa0586506d9d) }

var fileDescriptor_4595aa0586506d9d = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x49, 0xcd, 0x2b,
	0xce, 0x2f, 0x4a, 0xcb, 0xc9, 0x2f, 0x8f, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0xcc, 0x4b, 0xd7, 0xcf,
	0xcc, 0x2b, 0x28, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x42, 0xc8, 0xeb, 0x41,
	0xe5, 0xa5, 0x24, 0x10, 0x62, 0xfa, 0xa9, 0x15, 0x89, 0xb9, 0x05, 0x39, 0xa9, 0x10, 0xd5, 0x4a,
	0x76, 0x5c, 0xdc, 0xae, 0x10, 0x01, 0x9f, 0xcc, 0xe2, 0x12, 0x21, 0x7d, 0x2e, 0x0e, 0xa8, 0x7c,
	0xb1, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0xb0, 0x1e, 0x92, 0x79, 0x50, 0xa5, 0x41, 0x70,
	0x45, 0x4a, 0x15, 0x5c, 0x62, 0x48, 0xfa, 0xc3, 0x33, 0x4b, 0x32, 0x9c, 0xf3, 0xf3, 0x4a, 0x52,
	0x2b, 0x48, 0x37, 0x4a, 0x48, 0x97, 0x8b, 0x3d, 0x19, 0xa2, 0x57, 0x82, 0x49, 0x81, 0x11, 0x97,
	0x7a, 0x98, 0x1a, 0xa5, 0x63, 0x8c, 0x5c, 0xac, 0x9e, 0x20, 0x7f, 0x0b, 0x79, 0x70, 0xf1, 0x40,
	0x0d, 0x89, 0xcf, 0xc9, 0x2c, 0x2e, 0x91, 0x60, 0x04, 0xeb, 0x96, 0xd7, 0xc3, 0x0c, 0x08, 0x3d,
	0x24, 0xb7, 0x3a, 0x31, 0x69, 0x30, 0x7a, 0x30, 0x04, 0x71, 0xa7, 0x22, 0x79, 0x3f, 0x9b, 0x4b,
	0x12, 0xd9, 0xa4, 0xf8, 0xf2, 0xcc, 0x92, 0x8c, 0x78, 0x54, 0x47, 0x69, 0x11, 0x30, 0x16, 0x29,
	0x08, 0xa0, 0x36, 0x88, 0xa5, 0x62, 0x97, 0x65, 0xe3, 0x62, 0xc9, 0xce, 0xcc, 0x4b, 0x71, 0x12,
	0x8f, 0x12, 0xc2, 0x8c, 0xd2, 0x1f, 0x8c, 0x8c, 0x49, 0x6c, 0xe0, 0x28, 0x32, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x52, 0x9c, 0x9f, 0xb0, 0xf2, 0x01, 0x00, 0x00,
}
