// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow.serving/proto/model.proto

package tensorflow_serving

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Metadata for an inference request such as the model name and version.
type ModelSpec struct {
	// Required servable name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional choice of which version of the model to use.
	//
	// Recommended to be left unset in the common case. Should be specified only
	// when there is a strong version consistency requirement.
	//
	// When left unspecified, the system will serve the best available version.
	// This is typically the latest version, though during version transitions,
	// notably when serving on a fleet of instances, may be either the previous or
	// new version.
	//
	// Types that are valid to be assigned to VersionChoice:
	//	*ModelSpec_Version
	//	*ModelSpec_VersionLabel
	VersionChoice isModelSpec_VersionChoice `protobuf_oneof:"version_choice"`
	// A named signature to evaluate. If unspecified, the default signature will
	// be used.
	SignatureName        string   `protobuf:"bytes,3,opt,name=signature_name,json=signatureName,proto3" json:"signature_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelSpec) Reset()         { *m = ModelSpec{} }
func (m *ModelSpec) String() string { return proto.CompactTextString(m) }
func (*ModelSpec) ProtoMessage()    {}
func (*ModelSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fa6e74a378ca9d8, []int{0}
}

func (m *ModelSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelSpec.Unmarshal(m, b)
}
func (m *ModelSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelSpec.Marshal(b, m, deterministic)
}
func (m *ModelSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelSpec.Merge(m, src)
}
func (m *ModelSpec) XXX_Size() int {
	return xxx_messageInfo_ModelSpec.Size(m)
}
func (m *ModelSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ModelSpec proto.InternalMessageInfo

func (m *ModelSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isModelSpec_VersionChoice interface {
	isModelSpec_VersionChoice()
}

type ModelSpec_Version struct {
	Version *wrappers.Int64Value `protobuf:"bytes,2,opt,name=version,proto3,oneof"`
}

type ModelSpec_VersionLabel struct {
	VersionLabel string `protobuf:"bytes,4,opt,name=version_label,json=versionLabel,proto3,oneof"`
}

func (*ModelSpec_Version) isModelSpec_VersionChoice() {}

func (*ModelSpec_VersionLabel) isModelSpec_VersionChoice() {}

func (m *ModelSpec) GetVersionChoice() isModelSpec_VersionChoice {
	if m != nil {
		return m.VersionChoice
	}
	return nil
}

func (m *ModelSpec) GetVersion() *wrappers.Int64Value {
	if x, ok := m.GetVersionChoice().(*ModelSpec_Version); ok {
		return x.Version
	}
	return nil
}

func (m *ModelSpec) GetVersionLabel() string {
	if x, ok := m.GetVersionChoice().(*ModelSpec_VersionLabel); ok {
		return x.VersionLabel
	}
	return ""
}

func (m *ModelSpec) GetSignatureName() string {
	if m != nil {
		return m.SignatureName
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ModelSpec) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ModelSpec_Version)(nil),
		(*ModelSpec_VersionLabel)(nil),
	}
}

func init() {
	proto.RegisterType((*ModelSpec)(nil), "tensorflow.serving.ModelSpec")
}

func init() {
	proto.RegisterFile("tensorflow.serving/proto/model.proto", fileDescriptor_0fa6e74a378ca9d8)
}

var fileDescriptor_0fa6e74a378ca9d8 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8e, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x17, 0x37, 0x94, 0x45, 0x37, 0x24, 0xa7, 0xa2, 0x20, 0x43, 0x1c, 0xec, 0x94, 0x82,
	0x8a, 0xde, 0x77, 0x9a, 0xa0, 0x1e, 0x2a, 0x78, 0x2d, 0x69, 0x7d, 0x8d, 0x81, 0x34, 0x2f, 0x24,
	0x69, 0xfb, 0xaf, 0xf9, 0xa7, 0x79, 0x94, 0xa6, 0xad, 0x97, 0xdd, 0x3e, 0x3e, 0x7e, 0xef, 0xf7,
	0x3d, 0x7a, 0x17, 0xc0, 0x78, 0x74, 0x95, 0xc6, 0x8e, 0x7b, 0x70, 0xad, 0x32, 0x32, 0xb5, 0x0e,
	0x03, 0xa6, 0x35, 0x7e, 0x81, 0xe6, 0x31, 0x33, 0x76, 0x4c, 0x5d, 0xdd, 0x48, 0x44, 0xa9, 0x61,
	0xa0, 0x8b, 0xa6, 0x4a, 0x3b, 0x27, 0xac, 0x05, 0xe7, 0x87, 0x9b, 0xdb, 0x1f, 0x42, 0x97, 0x6f,
	0xbd, 0xe3, 0xc3, 0x42, 0xc9, 0x18, 0x5d, 0x18, 0x51, 0x43, 0x42, 0x36, 0x64, 0xb7, 0xcc, 0x62,
	0x66, 0xcf, 0xf4, 0xac, 0x05, 0xe7, 0x15, 0x9a, 0xe4, 0x64, 0x43, 0x76, 0xe7, 0xf7, 0xd7, 0x7c,
	0x70, 0xf2, 0xc9, 0xc9, 0x5f, 0x4c, 0x78, 0x7a, 0xfc, 0x14, 0xba, 0x81, 0xc3, 0x2c, 0x9b, 0x68,
	0xb6, 0xa5, 0xab, 0x31, 0xe6, 0x5a, 0x14, 0xa0, 0x93, 0x45, 0x6f, 0x3d, 0xcc, 0xb2, 0x8b, 0xb1,
	0x7e, 0xed, 0x5b, 0xb6, 0xa5, 0x6b, 0xaf, 0xa4, 0x11, 0xa1, 0x71, 0x90, 0xc7, 0xf5, 0x79, 0x5c,
	0x5f, 0xfd, 0xb7, 0xef, 0xa2, 0x86, 0xfd, 0x25, 0x5d, 0x4f, 0xb6, 0xf2, 0x1b, 0x55, 0x09, 0xfb,
	0xf9, 0x2f, 0x21, 0xc5, 0x69, 0x7c, 0xe2, 0xe1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xf3, 0xa6, 0x79,
	0x01, 0x22, 0x01, 0x00, 0x00,
}
