// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow_serving/config/model_server_config.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_tensorflow_5fserving_2fconfig_2fmodel_5fserver_5fconfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_tensorflow_5fserving_2fconfig_2fmodel_5fserver_5fconfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
#include "tensorflow_serving/config/logging_config.pb.h"
#include "tensorflow_serving/sources/storage_path/file_system_storage_path_source.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_tensorflow_5fserving_2fconfig_2fmodel_5fserver_5fconfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_tensorflow_5fserving_2fconfig_2fmodel_5fserver_5fconfig_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_tensorflow_5fserving_2fconfig_2fmodel_5fserver_5fconfig_2eproto;
namespace tensorflow {
namespace serving {
class ModelConfig;
class ModelConfigDefaultTypeInternal;
extern ModelConfigDefaultTypeInternal _ModelConfig_default_instance_;
class ModelConfigList;
class ModelConfigListDefaultTypeInternal;
extern ModelConfigListDefaultTypeInternal _ModelConfigList_default_instance_;
class ModelConfig_VersionLabelsEntry_DoNotUse;
class ModelConfig_VersionLabelsEntry_DoNotUseDefaultTypeInternal;
extern ModelConfig_VersionLabelsEntry_DoNotUseDefaultTypeInternal _ModelConfig_VersionLabelsEntry_DoNotUse_default_instance_;
class ModelServerConfig;
class ModelServerConfigDefaultTypeInternal;
extern ModelServerConfigDefaultTypeInternal _ModelServerConfig_default_instance_;
}  // namespace serving
}  // namespace tensorflow
PROTOBUF_NAMESPACE_OPEN
template<> ::tensorflow::serving::ModelConfig* Arena::CreateMaybeMessage<::tensorflow::serving::ModelConfig>(Arena*);
template<> ::tensorflow::serving::ModelConfigList* Arena::CreateMaybeMessage<::tensorflow::serving::ModelConfigList>(Arena*);
template<> ::tensorflow::serving::ModelConfig_VersionLabelsEntry_DoNotUse* Arena::CreateMaybeMessage<::tensorflow::serving::ModelConfig_VersionLabelsEntry_DoNotUse>(Arena*);
template<> ::tensorflow::serving::ModelServerConfig* Arena::CreateMaybeMessage<::tensorflow::serving::ModelServerConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace tensorflow {
namespace serving {

enum ModelType : int {
  MODEL_TYPE_UNSPECIFIED PROTOBUF_DEPRECATED_ENUM = 0,
  TENSORFLOW PROTOBUF_DEPRECATED_ENUM = 1,
  OTHER PROTOBUF_DEPRECATED_ENUM = 2,
  ModelType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ModelType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ModelType_IsValid(int value);
constexpr ModelType ModelType_MIN = MODEL_TYPE_UNSPECIFIED;
constexpr ModelType ModelType_MAX = OTHER;
constexpr int ModelType_ARRAYSIZE = ModelType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ModelType_descriptor();
template<typename T>
inline const std::string& ModelType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ModelType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ModelType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ModelType_descriptor(), enum_t_value);
}
inline bool ModelType_Parse(
    const std::string& name, ModelType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ModelType>(
    ModelType_descriptor(), name, value);
}
// ===================================================================

class ModelConfig_VersionLabelsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<ModelConfig_VersionLabelsEntry_DoNotUse, 
    std::string, ::PROTOBUF_NAMESPACE_ID::int64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<ModelConfig_VersionLabelsEntry_DoNotUse, 
    std::string, ::PROTOBUF_NAMESPACE_ID::int64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64,
    0 > SuperType;
  ModelConfig_VersionLabelsEntry_DoNotUse();
  ModelConfig_VersionLabelsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const ModelConfig_VersionLabelsEntry_DoNotUse& other);
  static const ModelConfig_VersionLabelsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const ModelConfig_VersionLabelsEntry_DoNotUse*>(&_ModelConfig_VersionLabelsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "tensorflow.serving.ModelConfig.VersionLabelsEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_tensorflow_5fserving_2fconfig_2fmodel_5fserver_5fconfig_2eproto);
    return ::descriptor_table_tensorflow_5fserving_2fconfig_2fmodel_5fserver_5fconfig_2eproto.file_level_metadata[0];
  }

  public:
};

// -------------------------------------------------------------------

class ModelConfig PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tensorflow.serving.ModelConfig) */ {
 public:
  inline ModelConfig() : ModelConfig(nullptr) {};
  virtual ~ModelConfig();

  ModelConfig(const ModelConfig& from);
  ModelConfig(ModelConfig&& from) noexcept
    : ModelConfig() {
    *this = ::std::move(from);
  }

  inline ModelConfig& operator=(const ModelConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModelConfig& operator=(ModelConfig&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ModelConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ModelConfig* internal_default_instance() {
    return reinterpret_cast<const ModelConfig*>(
               &_ModelConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ModelConfig& a, ModelConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(ModelConfig* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModelConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ModelConfig* New() const final {
    return CreateMaybeMessage<ModelConfig>(nullptr);
  }

  ModelConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ModelConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ModelConfig& from);
  void MergeFrom(const ModelConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModelConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tensorflow.serving.ModelConfig";
  }
  protected:
  explicit ModelConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_tensorflow_5fserving_2fconfig_2fmodel_5fserver_5fconfig_2eproto);
    return ::descriptor_table_tensorflow_5fserving_2fconfig_2fmodel_5fserver_5fconfig_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kVersionLabelsFieldNumber = 8,
    kNameFieldNumber = 1,
    kBasePathFieldNumber = 2,
    kModelPlatformFieldNumber = 4,
    kLoggingConfigFieldNumber = 6,
    kModelVersionPolicyFieldNumber = 7,
    kModelTypeFieldNumber = 3,
  };
  // map<string, int64> version_labels = 8;
  int version_labels_size() const;
  private:
  int _internal_version_labels_size() const;
  public:
  void clear_version_labels();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >&
      _internal_version_labels() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >*
      _internal_mutable_version_labels();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >&
      version_labels() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >*
      mutable_version_labels();

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_name(
      std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string base_path = 2;
  void clear_base_path();
  const std::string& base_path() const;
  void set_base_path(const std::string& value);
  void set_base_path(std::string&& value);
  void set_base_path(const char* value);
  void set_base_path(const char* value, size_t size);
  std::string* mutable_base_path();
  std::string* release_base_path();
  void set_allocated_base_path(std::string* base_path);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_base_path();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_base_path(
      std::string* base_path);
  private:
  const std::string& _internal_base_path() const;
  void _internal_set_base_path(const std::string& value);
  std::string* _internal_mutable_base_path();
  public:

  // string model_platform = 4;
  void clear_model_platform();
  const std::string& model_platform() const;
  void set_model_platform(const std::string& value);
  void set_model_platform(std::string&& value);
  void set_model_platform(const char* value);
  void set_model_platform(const char* value, size_t size);
  std::string* mutable_model_platform();
  std::string* release_model_platform();
  void set_allocated_model_platform(std::string* model_platform);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_model_platform();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_model_platform(
      std::string* model_platform);
  private:
  const std::string& _internal_model_platform() const;
  void _internal_set_model_platform(const std::string& value);
  std::string* _internal_mutable_model_platform();
  public:

  // .tensorflow.serving.LoggingConfig logging_config = 6;
  bool has_logging_config() const;
  private:
  bool _internal_has_logging_config() const;
  public:
  void clear_logging_config();
  const ::tensorflow::serving::LoggingConfig& logging_config() const;
  ::tensorflow::serving::LoggingConfig* release_logging_config();
  ::tensorflow::serving::LoggingConfig* mutable_logging_config();
  void set_allocated_logging_config(::tensorflow::serving::LoggingConfig* logging_config);
  private:
  const ::tensorflow::serving::LoggingConfig& _internal_logging_config() const;
  ::tensorflow::serving::LoggingConfig* _internal_mutable_logging_config();
  public:
  void unsafe_arena_set_allocated_logging_config(
      ::tensorflow::serving::LoggingConfig* logging_config);
  ::tensorflow::serving::LoggingConfig* unsafe_arena_release_logging_config();

  // .tensorflow.serving.FileSystemStoragePathSourceConfig.ServableVersionPolicy model_version_policy = 7;
  bool has_model_version_policy() const;
  private:
  bool _internal_has_model_version_policy() const;
  public:
  void clear_model_version_policy();
  const ::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy& model_version_policy() const;
  ::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy* release_model_version_policy();
  ::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy* mutable_model_version_policy();
  void set_allocated_model_version_policy(::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy* model_version_policy);
  private:
  const ::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy& _internal_model_version_policy() const;
  ::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy* _internal_mutable_model_version_policy();
  public:
  void unsafe_arena_set_allocated_model_version_policy(
      ::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy* model_version_policy);
  ::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy* unsafe_arena_release_model_version_policy();

  // .tensorflow.serving.ModelType model_type = 3 [deprecated = true];
  PROTOBUF_DEPRECATED void clear_model_type();
  PROTOBUF_DEPRECATED ::tensorflow::serving::ModelType model_type() const;
  PROTOBUF_DEPRECATED void set_model_type(::tensorflow::serving::ModelType value);
  private:
  ::tensorflow::serving::ModelType _internal_model_type() const;
  void _internal_set_model_type(::tensorflow::serving::ModelType value);
  public:

  // @@protoc_insertion_point(class_scope:tensorflow.serving.ModelConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      ModelConfig_VersionLabelsEntry_DoNotUse,
      std::string, ::PROTOBUF_NAMESPACE_ID::int64,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64,
      0 > version_labels_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr base_path_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr model_platform_;
  ::tensorflow::serving::LoggingConfig* logging_config_;
  ::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy* model_version_policy_;
  int model_type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_tensorflow_5fserving_2fconfig_2fmodel_5fserver_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class ModelConfigList PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tensorflow.serving.ModelConfigList) */ {
 public:
  inline ModelConfigList() : ModelConfigList(nullptr) {};
  virtual ~ModelConfigList();

  ModelConfigList(const ModelConfigList& from);
  ModelConfigList(ModelConfigList&& from) noexcept
    : ModelConfigList() {
    *this = ::std::move(from);
  }

  inline ModelConfigList& operator=(const ModelConfigList& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModelConfigList& operator=(ModelConfigList&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ModelConfigList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ModelConfigList* internal_default_instance() {
    return reinterpret_cast<const ModelConfigList*>(
               &_ModelConfigList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ModelConfigList& a, ModelConfigList& b) {
    a.Swap(&b);
  }
  inline void Swap(ModelConfigList* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModelConfigList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ModelConfigList* New() const final {
    return CreateMaybeMessage<ModelConfigList>(nullptr);
  }

  ModelConfigList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ModelConfigList>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ModelConfigList& from);
  void MergeFrom(const ModelConfigList& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModelConfigList* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tensorflow.serving.ModelConfigList";
  }
  protected:
  explicit ModelConfigList(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_tensorflow_5fserving_2fconfig_2fmodel_5fserver_5fconfig_2eproto);
    return ::descriptor_table_tensorflow_5fserving_2fconfig_2fmodel_5fserver_5fconfig_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kConfigFieldNumber = 1,
  };
  // repeated .tensorflow.serving.ModelConfig config = 1;
  int config_size() const;
  private:
  int _internal_config_size() const;
  public:
  void clear_config();
  ::tensorflow::serving::ModelConfig* mutable_config(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::serving::ModelConfig >*
      mutable_config();
  private:
  const ::tensorflow::serving::ModelConfig& _internal_config(int index) const;
  ::tensorflow::serving::ModelConfig* _internal_add_config();
  public:
  const ::tensorflow::serving::ModelConfig& config(int index) const;
  ::tensorflow::serving::ModelConfig* add_config();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::serving::ModelConfig >&
      config() const;

  // @@protoc_insertion_point(class_scope:tensorflow.serving.ModelConfigList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::serving::ModelConfig > config_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_tensorflow_5fserving_2fconfig_2fmodel_5fserver_5fconfig_2eproto;
};
// -------------------------------------------------------------------

class ModelServerConfig PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tensorflow.serving.ModelServerConfig) */ {
 public:
  inline ModelServerConfig() : ModelServerConfig(nullptr) {};
  virtual ~ModelServerConfig();

  ModelServerConfig(const ModelServerConfig& from);
  ModelServerConfig(ModelServerConfig&& from) noexcept
    : ModelServerConfig() {
    *this = ::std::move(from);
  }

  inline ModelServerConfig& operator=(const ModelServerConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline ModelServerConfig& operator=(ModelServerConfig&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ModelServerConfig& default_instance();

  enum ConfigCase {
    kModelConfigList = 1,
    kCustomModelConfig = 2,
    CONFIG_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ModelServerConfig* internal_default_instance() {
    return reinterpret_cast<const ModelServerConfig*>(
               &_ModelServerConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ModelServerConfig& a, ModelServerConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(ModelServerConfig* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ModelServerConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ModelServerConfig* New() const final {
    return CreateMaybeMessage<ModelServerConfig>(nullptr);
  }

  ModelServerConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ModelServerConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ModelServerConfig& from);
  void MergeFrom(const ModelServerConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModelServerConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tensorflow.serving.ModelServerConfig";
  }
  protected:
  explicit ModelServerConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_tensorflow_5fserving_2fconfig_2fmodel_5fserver_5fconfig_2eproto);
    return ::descriptor_table_tensorflow_5fserving_2fconfig_2fmodel_5fserver_5fconfig_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kModelConfigListFieldNumber = 1,
    kCustomModelConfigFieldNumber = 2,
  };
  // .tensorflow.serving.ModelConfigList model_config_list = 1;
  bool has_model_config_list() const;
  private:
  bool _internal_has_model_config_list() const;
  public:
  void clear_model_config_list();
  const ::tensorflow::serving::ModelConfigList& model_config_list() const;
  ::tensorflow::serving::ModelConfigList* release_model_config_list();
  ::tensorflow::serving::ModelConfigList* mutable_model_config_list();
  void set_allocated_model_config_list(::tensorflow::serving::ModelConfigList* model_config_list);
  private:
  const ::tensorflow::serving::ModelConfigList& _internal_model_config_list() const;
  ::tensorflow::serving::ModelConfigList* _internal_mutable_model_config_list();
  public:
  void unsafe_arena_set_allocated_model_config_list(
      ::tensorflow::serving::ModelConfigList* model_config_list);
  ::tensorflow::serving::ModelConfigList* unsafe_arena_release_model_config_list();

  // .google.protobuf.Any custom_model_config = 2;
  bool has_custom_model_config() const;
  private:
  bool _internal_has_custom_model_config() const;
  public:
  void clear_custom_model_config();
  const PROTOBUF_NAMESPACE_ID::Any& custom_model_config() const;
  PROTOBUF_NAMESPACE_ID::Any* release_custom_model_config();
  PROTOBUF_NAMESPACE_ID::Any* mutable_custom_model_config();
  void set_allocated_custom_model_config(PROTOBUF_NAMESPACE_ID::Any* custom_model_config);
  private:
  const PROTOBUF_NAMESPACE_ID::Any& _internal_custom_model_config() const;
  PROTOBUF_NAMESPACE_ID::Any* _internal_mutable_custom_model_config();
  public:
  void unsafe_arena_set_allocated_custom_model_config(
      PROTOBUF_NAMESPACE_ID::Any* custom_model_config);
  PROTOBUF_NAMESPACE_ID::Any* unsafe_arena_release_custom_model_config();

  void clear_config();
  ConfigCase config_case() const;
  // @@protoc_insertion_point(class_scope:tensorflow.serving.ModelServerConfig)
 private:
  class _Internal;
  void set_has_model_config_list();
  void set_has_custom_model_config();

  inline bool has_config() const;
  inline void clear_has_config();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  union ConfigUnion {
    ConfigUnion() {}
    ::tensorflow::serving::ModelConfigList* model_config_list_;
    PROTOBUF_NAMESPACE_ID::Any* custom_model_config_;
  } config_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_tensorflow_5fserving_2fconfig_2fmodel_5fserver_5fconfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ModelConfig

// string name = 1;
inline void ModelConfig::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ModelConfig::name() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.ModelConfig.name)
  return _internal_name();
}
inline void ModelConfig::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:tensorflow.serving.ModelConfig.name)
}
inline std::string* ModelConfig::mutable_name() {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.ModelConfig.name)
  return _internal_mutable_name();
}
inline const std::string& ModelConfig::_internal_name() const {
  return name_.Get();
}
inline void ModelConfig::_internal_set_name(const std::string& value) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ModelConfig::set_name(std::string&& value) {
  
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:tensorflow.serving.ModelConfig.name)
}
inline void ModelConfig::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:tensorflow.serving.ModelConfig.name)
}
inline void ModelConfig::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:tensorflow.serving.ModelConfig.name)
}
inline std::string* ModelConfig::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ModelConfig::release_name() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.ModelConfig.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ModelConfig::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.ModelConfig.name)
}
inline std::string* ModelConfig::unsafe_arena_release_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.serving.ModelConfig.name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ModelConfig::unsafe_arena_set_allocated_name(
    std::string* name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (name != nullptr) {
    
  } else {
    
  }
  name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.ModelConfig.name)
}

// string base_path = 2;
inline void ModelConfig::clear_base_path() {
  base_path_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ModelConfig::base_path() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.ModelConfig.base_path)
  return _internal_base_path();
}
inline void ModelConfig::set_base_path(const std::string& value) {
  _internal_set_base_path(value);
  // @@protoc_insertion_point(field_set:tensorflow.serving.ModelConfig.base_path)
}
inline std::string* ModelConfig::mutable_base_path() {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.ModelConfig.base_path)
  return _internal_mutable_base_path();
}
inline const std::string& ModelConfig::_internal_base_path() const {
  return base_path_.Get();
}
inline void ModelConfig::_internal_set_base_path(const std::string& value) {
  
  base_path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ModelConfig::set_base_path(std::string&& value) {
  
  base_path_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:tensorflow.serving.ModelConfig.base_path)
}
inline void ModelConfig::set_base_path(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  base_path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:tensorflow.serving.ModelConfig.base_path)
}
inline void ModelConfig::set_base_path(const char* value,
    size_t size) {
  
  base_path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:tensorflow.serving.ModelConfig.base_path)
}
inline std::string* ModelConfig::_internal_mutable_base_path() {
  
  return base_path_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ModelConfig::release_base_path() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.ModelConfig.base_path)
  return base_path_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ModelConfig::set_allocated_base_path(std::string* base_path) {
  if (base_path != nullptr) {
    
  } else {
    
  }
  base_path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), base_path,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.ModelConfig.base_path)
}
inline std::string* ModelConfig::unsafe_arena_release_base_path() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.serving.ModelConfig.base_path)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return base_path_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ModelConfig::unsafe_arena_set_allocated_base_path(
    std::string* base_path) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (base_path != nullptr) {
    
  } else {
    
  }
  base_path_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      base_path, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.ModelConfig.base_path)
}

// .tensorflow.serving.ModelType model_type = 3 [deprecated = true];
inline void ModelConfig::clear_model_type() {
  model_type_ = 0;
}
inline ::tensorflow::serving::ModelType ModelConfig::_internal_model_type() const {
  return static_cast< ::tensorflow::serving::ModelType >(model_type_);
}
inline ::tensorflow::serving::ModelType ModelConfig::model_type() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.ModelConfig.model_type)
  return _internal_model_type();
}
inline void ModelConfig::_internal_set_model_type(::tensorflow::serving::ModelType value) {
  
  model_type_ = value;
}
inline void ModelConfig::set_model_type(::tensorflow::serving::ModelType value) {
  _internal_set_model_type(value);
  // @@protoc_insertion_point(field_set:tensorflow.serving.ModelConfig.model_type)
}

// string model_platform = 4;
inline void ModelConfig::clear_model_platform() {
  model_platform_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ModelConfig::model_platform() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.ModelConfig.model_platform)
  return _internal_model_platform();
}
inline void ModelConfig::set_model_platform(const std::string& value) {
  _internal_set_model_platform(value);
  // @@protoc_insertion_point(field_set:tensorflow.serving.ModelConfig.model_platform)
}
inline std::string* ModelConfig::mutable_model_platform() {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.ModelConfig.model_platform)
  return _internal_mutable_model_platform();
}
inline const std::string& ModelConfig::_internal_model_platform() const {
  return model_platform_.Get();
}
inline void ModelConfig::_internal_set_model_platform(const std::string& value) {
  
  model_platform_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ModelConfig::set_model_platform(std::string&& value) {
  
  model_platform_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:tensorflow.serving.ModelConfig.model_platform)
}
inline void ModelConfig::set_model_platform(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  model_platform_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:tensorflow.serving.ModelConfig.model_platform)
}
inline void ModelConfig::set_model_platform(const char* value,
    size_t size) {
  
  model_platform_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:tensorflow.serving.ModelConfig.model_platform)
}
inline std::string* ModelConfig::_internal_mutable_model_platform() {
  
  return model_platform_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ModelConfig::release_model_platform() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.ModelConfig.model_platform)
  return model_platform_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ModelConfig::set_allocated_model_platform(std::string* model_platform) {
  if (model_platform != nullptr) {
    
  } else {
    
  }
  model_platform_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), model_platform,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.ModelConfig.model_platform)
}
inline std::string* ModelConfig::unsafe_arena_release_model_platform() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.serving.ModelConfig.model_platform)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return model_platform_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ModelConfig::unsafe_arena_set_allocated_model_platform(
    std::string* model_platform) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (model_platform != nullptr) {
    
  } else {
    
  }
  model_platform_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      model_platform, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.ModelConfig.model_platform)
}

// .tensorflow.serving.FileSystemStoragePathSourceConfig.ServableVersionPolicy model_version_policy = 7;
inline bool ModelConfig::_internal_has_model_version_policy() const {
  return this != internal_default_instance() && model_version_policy_ != nullptr;
}
inline bool ModelConfig::has_model_version_policy() const {
  return _internal_has_model_version_policy();
}
inline const ::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy& ModelConfig::_internal_model_version_policy() const {
  const ::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy* p = model_version_policy_;
  return p != nullptr ? *p : *reinterpret_cast<const ::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy*>(
      &::tensorflow::serving::_FileSystemStoragePathSourceConfig_ServableVersionPolicy_default_instance_);
}
inline const ::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy& ModelConfig::model_version_policy() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.ModelConfig.model_version_policy)
  return _internal_model_version_policy();
}
inline void ModelConfig::unsafe_arena_set_allocated_model_version_policy(
    ::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy* model_version_policy) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(model_version_policy_);
  }
  model_version_policy_ = model_version_policy;
  if (model_version_policy) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.ModelConfig.model_version_policy)
}
inline ::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy* ModelConfig::release_model_version_policy() {
  auto temp = unsafe_arena_release_model_version_policy();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy* ModelConfig::unsafe_arena_release_model_version_policy() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.ModelConfig.model_version_policy)
  
  ::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy* temp = model_version_policy_;
  model_version_policy_ = nullptr;
  return temp;
}
inline ::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy* ModelConfig::_internal_mutable_model_version_policy() {
  
  if (model_version_policy_ == nullptr) {
    auto* p = CreateMaybeMessage<::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy>(GetArena());
    model_version_policy_ = p;
  }
  return model_version_policy_;
}
inline ::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy* ModelConfig::mutable_model_version_policy() {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.ModelConfig.model_version_policy)
  return _internal_mutable_model_version_policy();
}
inline void ModelConfig::set_allocated_model_version_policy(::tensorflow::serving::FileSystemStoragePathSourceConfig_ServableVersionPolicy* model_version_policy) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(model_version_policy_);
  }
  if (model_version_policy) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(model_version_policy)->GetArena();
    if (message_arena != submessage_arena) {
      model_version_policy = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, model_version_policy, submessage_arena);
    }
    
  } else {
    
  }
  model_version_policy_ = model_version_policy;
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.ModelConfig.model_version_policy)
}

// map<string, int64> version_labels = 8;
inline int ModelConfig::_internal_version_labels_size() const {
  return version_labels_.size();
}
inline int ModelConfig::version_labels_size() const {
  return _internal_version_labels_size();
}
inline void ModelConfig::clear_version_labels() {
  version_labels_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >&
ModelConfig::_internal_version_labels() const {
  return version_labels_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >&
ModelConfig::version_labels() const {
  // @@protoc_insertion_point(field_map:tensorflow.serving.ModelConfig.version_labels)
  return _internal_version_labels();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >*
ModelConfig::_internal_mutable_version_labels() {
  return version_labels_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int64 >*
ModelConfig::mutable_version_labels() {
  // @@protoc_insertion_point(field_mutable_map:tensorflow.serving.ModelConfig.version_labels)
  return _internal_mutable_version_labels();
}

// .tensorflow.serving.LoggingConfig logging_config = 6;
inline bool ModelConfig::_internal_has_logging_config() const {
  return this != internal_default_instance() && logging_config_ != nullptr;
}
inline bool ModelConfig::has_logging_config() const {
  return _internal_has_logging_config();
}
inline const ::tensorflow::serving::LoggingConfig& ModelConfig::_internal_logging_config() const {
  const ::tensorflow::serving::LoggingConfig* p = logging_config_;
  return p != nullptr ? *p : *reinterpret_cast<const ::tensorflow::serving::LoggingConfig*>(
      &::tensorflow::serving::_LoggingConfig_default_instance_);
}
inline const ::tensorflow::serving::LoggingConfig& ModelConfig::logging_config() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.ModelConfig.logging_config)
  return _internal_logging_config();
}
inline void ModelConfig::unsafe_arena_set_allocated_logging_config(
    ::tensorflow::serving::LoggingConfig* logging_config) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(logging_config_);
  }
  logging_config_ = logging_config;
  if (logging_config) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.ModelConfig.logging_config)
}
inline ::tensorflow::serving::LoggingConfig* ModelConfig::release_logging_config() {
  auto temp = unsafe_arena_release_logging_config();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::tensorflow::serving::LoggingConfig* ModelConfig::unsafe_arena_release_logging_config() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.ModelConfig.logging_config)
  
  ::tensorflow::serving::LoggingConfig* temp = logging_config_;
  logging_config_ = nullptr;
  return temp;
}
inline ::tensorflow::serving::LoggingConfig* ModelConfig::_internal_mutable_logging_config() {
  
  if (logging_config_ == nullptr) {
    auto* p = CreateMaybeMessage<::tensorflow::serving::LoggingConfig>(GetArena());
    logging_config_ = p;
  }
  return logging_config_;
}
inline ::tensorflow::serving::LoggingConfig* ModelConfig::mutable_logging_config() {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.ModelConfig.logging_config)
  return _internal_mutable_logging_config();
}
inline void ModelConfig::set_allocated_logging_config(::tensorflow::serving::LoggingConfig* logging_config) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(logging_config_);
  }
  if (logging_config) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(logging_config)->GetArena();
    if (message_arena != submessage_arena) {
      logging_config = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, logging_config, submessage_arena);
    }
    
  } else {
    
  }
  logging_config_ = logging_config;
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.ModelConfig.logging_config)
}

// -------------------------------------------------------------------

// ModelConfigList

// repeated .tensorflow.serving.ModelConfig config = 1;
inline int ModelConfigList::_internal_config_size() const {
  return config_.size();
}
inline int ModelConfigList::config_size() const {
  return _internal_config_size();
}
inline void ModelConfigList::clear_config() {
  config_.Clear();
}
inline ::tensorflow::serving::ModelConfig* ModelConfigList::mutable_config(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.ModelConfigList.config)
  return config_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::serving::ModelConfig >*
ModelConfigList::mutable_config() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.serving.ModelConfigList.config)
  return &config_;
}
inline const ::tensorflow::serving::ModelConfig& ModelConfigList::_internal_config(int index) const {
  return config_.Get(index);
}
inline const ::tensorflow::serving::ModelConfig& ModelConfigList::config(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.ModelConfigList.config)
  return _internal_config(index);
}
inline ::tensorflow::serving::ModelConfig* ModelConfigList::_internal_add_config() {
  return config_.Add();
}
inline ::tensorflow::serving::ModelConfig* ModelConfigList::add_config() {
  // @@protoc_insertion_point(field_add:tensorflow.serving.ModelConfigList.config)
  return _internal_add_config();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::serving::ModelConfig >&
ModelConfigList::config() const {
  // @@protoc_insertion_point(field_list:tensorflow.serving.ModelConfigList.config)
  return config_;
}

// -------------------------------------------------------------------

// ModelServerConfig

// .tensorflow.serving.ModelConfigList model_config_list = 1;
inline bool ModelServerConfig::_internal_has_model_config_list() const {
  return config_case() == kModelConfigList;
}
inline bool ModelServerConfig::has_model_config_list() const {
  return _internal_has_model_config_list();
}
inline void ModelServerConfig::set_has_model_config_list() {
  _oneof_case_[0] = kModelConfigList;
}
inline void ModelServerConfig::clear_model_config_list() {
  if (_internal_has_model_config_list()) {
    if (GetArena() == nullptr) {
      delete config_.model_config_list_;
    }
    clear_has_config();
  }
}
inline ::tensorflow::serving::ModelConfigList* ModelServerConfig::release_model_config_list() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.ModelServerConfig.model_config_list)
  if (_internal_has_model_config_list()) {
    clear_has_config();
      ::tensorflow::serving::ModelConfigList* temp = config_.model_config_list_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    config_.model_config_list_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::tensorflow::serving::ModelConfigList& ModelServerConfig::_internal_model_config_list() const {
  return _internal_has_model_config_list()
      ? *config_.model_config_list_
      : *reinterpret_cast< ::tensorflow::serving::ModelConfigList*>(&::tensorflow::serving::_ModelConfigList_default_instance_);
}
inline const ::tensorflow::serving::ModelConfigList& ModelServerConfig::model_config_list() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.ModelServerConfig.model_config_list)
  return _internal_model_config_list();
}
inline ::tensorflow::serving::ModelConfigList* ModelServerConfig::unsafe_arena_release_model_config_list() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.serving.ModelServerConfig.model_config_list)
  if (_internal_has_model_config_list()) {
    clear_has_config();
    ::tensorflow::serving::ModelConfigList* temp = config_.model_config_list_;
    config_.model_config_list_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ModelServerConfig::unsafe_arena_set_allocated_model_config_list(::tensorflow::serving::ModelConfigList* model_config_list) {
  clear_config();
  if (model_config_list) {
    set_has_model_config_list();
    config_.model_config_list_ = model_config_list;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.ModelServerConfig.model_config_list)
}
inline ::tensorflow::serving::ModelConfigList* ModelServerConfig::_internal_mutable_model_config_list() {
  if (!_internal_has_model_config_list()) {
    clear_config();
    set_has_model_config_list();
    config_.model_config_list_ = CreateMaybeMessage< ::tensorflow::serving::ModelConfigList >(GetArena());
  }
  return config_.model_config_list_;
}
inline ::tensorflow::serving::ModelConfigList* ModelServerConfig::mutable_model_config_list() {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.ModelServerConfig.model_config_list)
  return _internal_mutable_model_config_list();
}

// .google.protobuf.Any custom_model_config = 2;
inline bool ModelServerConfig::_internal_has_custom_model_config() const {
  return config_case() == kCustomModelConfig;
}
inline bool ModelServerConfig::has_custom_model_config() const {
  return _internal_has_custom_model_config();
}
inline void ModelServerConfig::set_has_custom_model_config() {
  _oneof_case_[0] = kCustomModelConfig;
}
inline PROTOBUF_NAMESPACE_ID::Any* ModelServerConfig::release_custom_model_config() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.ModelServerConfig.custom_model_config)
  if (_internal_has_custom_model_config()) {
    clear_has_config();
      PROTOBUF_NAMESPACE_ID::Any* temp = config_.custom_model_config_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    config_.custom_model_config_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const PROTOBUF_NAMESPACE_ID::Any& ModelServerConfig::_internal_custom_model_config() const {
  return _internal_has_custom_model_config()
      ? *config_.custom_model_config_
      : *reinterpret_cast< PROTOBUF_NAMESPACE_ID::Any*>(&PROTOBUF_NAMESPACE_ID::_Any_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Any& ModelServerConfig::custom_model_config() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.ModelServerConfig.custom_model_config)
  return _internal_custom_model_config();
}
inline PROTOBUF_NAMESPACE_ID::Any* ModelServerConfig::unsafe_arena_release_custom_model_config() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.serving.ModelServerConfig.custom_model_config)
  if (_internal_has_custom_model_config()) {
    clear_has_config();
    PROTOBUF_NAMESPACE_ID::Any* temp = config_.custom_model_config_;
    config_.custom_model_config_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ModelServerConfig::unsafe_arena_set_allocated_custom_model_config(PROTOBUF_NAMESPACE_ID::Any* custom_model_config) {
  clear_config();
  if (custom_model_config) {
    set_has_custom_model_config();
    config_.custom_model_config_ = custom_model_config;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.ModelServerConfig.custom_model_config)
}
inline PROTOBUF_NAMESPACE_ID::Any* ModelServerConfig::_internal_mutable_custom_model_config() {
  if (!_internal_has_custom_model_config()) {
    clear_config();
    set_has_custom_model_config();
    config_.custom_model_config_ = CreateMaybeMessage< PROTOBUF_NAMESPACE_ID::Any >(GetArena());
  }
  return config_.custom_model_config_;
}
inline PROTOBUF_NAMESPACE_ID::Any* ModelServerConfig::mutable_custom_model_config() {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.ModelServerConfig.custom_model_config)
  return _internal_mutable_custom_model_config();
}

inline bool ModelServerConfig::has_config() const {
  return config_case() != CONFIG_NOT_SET;
}
inline void ModelServerConfig::clear_has_config() {
  _oneof_case_[0] = CONFIG_NOT_SET;
}
inline ModelServerConfig::ConfigCase ModelServerConfig::config_case() const {
  return ModelServerConfig::ConfigCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace serving
}  // namespace tensorflow

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::tensorflow::serving::ModelType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::tensorflow::serving::ModelType>() {
  return ::tensorflow::serving::ModelType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_tensorflow_5fserving_2fconfig_2fmodel_5fserver_5fconfig_2eproto
